const ADS_HAS_ERRORED = 'ADS_HAS_ERRORED'
const ADS_ARE_LOADING = 'ADS_ARE_LOADING'
const AD_FETCH_DATA_SUCCESS = 'AD_FETCH_DATA_SUCCESS'
const ADD_AD_FETCH_DATA_SUCCESS = 'ADD_AD_FETCH_DATA_SUCCESS'
const RESET_AD_FETCH_DATA_SUCCESS = 'RESET_AD_FETCH_DATA_SUCCESS'

export {
  ADS_HAS_ERRORED,
  ADS_ARE_LOADING,
  AD_FETCH_DATA_SUCCESS,
  ADD_AD_FETCH_DATA_SUCCESS,
  RESET_AD_FETCH_DATA_SUCCESS
}