const ADS_HAS_ERRORED = 'ADS_HAS_ERRORED'
const ADS_ARE_LOADING = 'ADS_ARE_LOADING'
const AD_FETCH_DATA_SUCCESS = 'AD_FETCH_DATA_SUCCESS'
const ADD_AD_FETCH_DATA_SUCCESS = 'ADD_AD_FETCH_DATA_SUCCESS'
const RESET_AD_FETCH_DATA_SUCCESS = 'RESET_AD_FETCH_DATA_SUCCESS'
const IMG_URL_CHANGED = 'IMG_URL_CHANGED'
const LINK_URL_CHANGED = 'LINK_URL_CHANGED'
const TITLE_CHANGED = 'TITLE_CHANGED'
const ID_SAVED = 'ID_SAVED'
const GET_USER_ADDRESS_SUCESS = 'GET_USER_ADDRESS_SUCESS'
const SET_CONTRACT = 'SET_CONTRACT'
const METAMASK_INJECTED_SUCCESS = 'METAMASK_INJECTED_SUCCESS'

export {
  ADS_HAS_ERRORED,
  ADS_ARE_LOADING,
  AD_FETCH_DATA_SUCCESS,
  ADD_AD_FETCH_DATA_SUCCESS,
  RESET_AD_FETCH_DATA_SUCCESS,
  IMG_URL_CHANGED,
  LINK_URL_CHANGED,
  TITLE_CHANGED,
  ID_SAVED,
  GET_USER_ADDRESS_SUCESS,
  SET_CONTRACT,
  METAMASK_INJECTED_SUCCESS
}